#!/usr/bin/env bash

WRAPPER_COMMAND=""
WRAPPER_NAME=""

hash leaks 2>/dev/null
if [ $? -eq 0 ]; then
    WRAPPER_COMMAND="leaks -atExit --"
    WRAPPER_NAME="leaks"
fi

hash valgrind 2>/dev/null
if [ $? -eq 0 ]; then
    WRAPPER_COMMAND="valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose --error-exitcode=1"
    WRAPPER_NAME="valgrind"
fi

if [ ${#WRAPPER_NAME} -gt 0 ]; then
    echo "Running with $WRAPPER_NAME..."
fi
$WRAPPER_COMMAND $(dirname $0)/../../out/intermediate/{# EXE_NAME #} $@
