// This file was automatically generated by Beschi v0.1.12
// <https://github.com/sjml/beschi>
// Do not edit directly.

using System;
using System.IO;
using System.Text;
using System.Collections.Generic;

namespace AppMessages
{
    public enum MessageType
    {
        Vector3MessageType = 1,
        NewCharacterMessageType = 2,
        CharacterJoinedTeamType = 3,
    }

    public abstract class Message {
        abstract public MessageType GetMessageType();
        abstract public void WriteBytes(BinaryWriter bw, bool tag);
        abstract public int GetSizeInBytes();

        public static Message[] ProcessRawBytes(BinaryReader br)
        {
            List<Message> msgList = new List<Message>();
            while (br.BaseStream.Position < br.BaseStream.Length)
            {
                byte msgType = br.ReadByte();
                switch (msgType)
                {
                    case (byte)MessageType.Vector3MessageType:
                        msgList.Add(Vector3Message.FromBytes(br));
                        break;
                    case (byte)MessageType.NewCharacterMessageType:
                        msgList.Add(NewCharacterMessage.FromBytes(br));
                        break;
                    case (byte)MessageType.CharacterJoinedTeamType:
                        msgList.Add(CharacterJoinedTeam.FromBytes(br));
                        break;
                    default:
                        msgList.Add(null);
                        break;
                }
                if (msgList[msgList.Count-1] == null) {
                    break;
                }
            }
            return msgList.ToArray();
        }
    }

    public class Color
    {
        public float red;
        public float green;
        public float blue;
        public float alpha;

        public static Color FromBytes(BinaryReader br)
        {
            Color nColor = new Color();
            nColor.red = br.ReadSingle();
            nColor.green = br.ReadSingle();
            nColor.blue = br.ReadSingle();
            nColor.alpha = br.ReadSingle();
            return nColor;
        }
        public void WriteBytes(BinaryWriter bw)
        {
            bw.Write(this.red);
            bw.Write(this.green);
            bw.Write(this.blue);
            bw.Write(this.alpha);
        }

    }

    public class Spectrum
    {
        public Color defaultColor = new Color();
        public List<Color> colors = new List<Color>();

        public static Spectrum FromBytes(BinaryReader br)
        {
            Spectrum nSpectrum = new Spectrum();
            nSpectrum.defaultColor = Color.FromBytes(br);
            ushort colors_Length = br.ReadUInt16();
            nSpectrum.colors = new List<Color>();
            for (int i3 = 0; i3 < colors_Length; i3++)
            {
                Color el = Color.FromBytes(br);
                nSpectrum.colors.Add(el);
            }
            return nSpectrum;
        }
        public void WriteBytes(BinaryWriter bw)
        {
            this.defaultColor.WriteBytes(bw);
            bw.Write((ushort)this.colors.Count);
            foreach (Color el in this.colors)
            {
                el.WriteBytes(bw);
            }
        }

    }

    public class Vector3Message : Message
    {
        public float x;
        public float y;
        public float z;

        public override MessageType GetMessageType() { return MessageType.Vector3MessageType; }

        public override int GetSizeInBytes()
        {
            return 12;
        }

        public static Vector3Message FromBytes(BinaryReader br)
        {
            try
            {
                Vector3Message nVector3Message = new Vector3Message();
                nVector3Message.x = br.ReadSingle();
                nVector3Message.y = br.ReadSingle();
                nVector3Message.z = br.ReadSingle();
                return nVector3Message;
            }
            catch (System.IO.EndOfStreamException)
            {
                return null;
            }
        }
        public override void WriteBytes(BinaryWriter bw, bool tag)
        {
            if (tag)
            {
                bw.Write((byte)MessageType.Vector3MessageType);
            }
            bw.Write(this.x);
            bw.Write(this.y);
            bw.Write(this.z);
        }

    }

    public class NewCharacterMessage : Message
    {
        public ulong id;
        public string characterName = "";
        public ushort strength;
        public ushort intelligence;
        public ushort dexterity;
        public uint goldInWallet;
        public List<string> nicknames = new List<string>();

        public override MessageType GetMessageType() { return MessageType.NewCharacterMessageType; }

        public override int GetSizeInBytes()
        {
            int size = 0;
            size += this.characterName.Length;
            foreach (string s in this.nicknames)
            {
                size += 1 + System.Text.Encoding.UTF8.GetBytes(s).Length;
            }
            size += 21;
            return size;
        }

        public static NewCharacterMessage FromBytes(BinaryReader br)
        {
            try
            {
                NewCharacterMessage nNewCharacterMessage = new NewCharacterMessage();
                nNewCharacterMessage.id = br.ReadUInt64();
                byte characterName_Length = br.ReadByte();
                byte[] characterName_Buffer = br.ReadBytes((int)characterName_Length);
                nNewCharacterMessage.characterName = System.Text.Encoding.UTF8.GetString(characterName_Buffer);
                nNewCharacterMessage.strength = br.ReadUInt16();
                nNewCharacterMessage.intelligence = br.ReadUInt16();
                nNewCharacterMessage.dexterity = br.ReadUInt16();
                nNewCharacterMessage.goldInWallet = br.ReadUInt32();
                ushort nicknames_Length = br.ReadUInt16();
                nNewCharacterMessage.nicknames = new List<string>();
                for (int i4 = 0; i4 < nicknames_Length; i4++)
                {
                    byte string_el_Length = br.ReadByte();
                    byte[] string_el_Buffer = br.ReadBytes((int)string_el_Length);
                    string el = System.Text.Encoding.UTF8.GetString(string_el_Buffer);
                    nNewCharacterMessage.nicknames.Add(el);
                }
                return nNewCharacterMessage;
            }
            catch (System.IO.EndOfStreamException)
            {
                return null;
            }
        }
        public override void WriteBytes(BinaryWriter bw, bool tag)
        {
            if (tag)
            {
                bw.Write((byte)MessageType.NewCharacterMessageType);
            }
            bw.Write(this.id);
            byte[] characterName_Buffer = System.Text.Encoding.UTF8.GetBytes(this.characterName);
            bw.Write((byte)characterName_Buffer.Length);
            bw.Write(characterName_Buffer);
            bw.Write(this.strength);
            bw.Write(this.intelligence);
            bw.Write(this.dexterity);
            bw.Write(this.goldInWallet);
            bw.Write((ushort)this.nicknames.Count);
            foreach (string el in this.nicknames)
            {
                byte[] el_Buffer = System.Text.Encoding.UTF8.GetBytes(el);
                bw.Write((byte)el_Buffer.Length);
                bw.Write(el_Buffer);
            }
        }

    }

    public class CharacterJoinedTeam : Message
    {
        public ulong characterID;
        public string teamName = "";
        public List<Color> teamColors = new List<Color>();

        public override MessageType GetMessageType() { return MessageType.CharacterJoinedTeamType; }

        public override int GetSizeInBytes()
        {
            int size = 0;
            size += this.teamName.Length;
            size += this.teamColors.Count * 16;
            size += 11;
            return size;
        }

        public static CharacterJoinedTeam FromBytes(BinaryReader br)
        {
            try
            {
                CharacterJoinedTeam nCharacterJoinedTeam = new CharacterJoinedTeam();
                nCharacterJoinedTeam.characterID = br.ReadUInt64();
                byte teamName_Length = br.ReadByte();
                byte[] teamName_Buffer = br.ReadBytes((int)teamName_Length);
                nCharacterJoinedTeam.teamName = System.Text.Encoding.UTF8.GetString(teamName_Buffer);
                ushort teamColors_Length = br.ReadUInt16();
                nCharacterJoinedTeam.teamColors = new List<Color>();
                for (int i4 = 0; i4 < teamColors_Length; i4++)
                {
                    Color el = Color.FromBytes(br);
                    nCharacterJoinedTeam.teamColors.Add(el);
                }
                return nCharacterJoinedTeam;
            }
            catch (System.IO.EndOfStreamException)
            {
                return null;
            }
        }
        public override void WriteBytes(BinaryWriter bw, bool tag)
        {
            if (tag)
            {
                bw.Write((byte)MessageType.CharacterJoinedTeamType);
            }
            bw.Write(this.characterID);
            byte[] teamName_Buffer = System.Text.Encoding.UTF8.GetBytes(this.teamName);
            bw.Write((byte)teamName_Buffer.Length);
            bw.Write(teamName_Buffer);
            bw.Write((ushort)this.teamColors.Count);
            foreach (Color el in this.teamColors)
            {
                el.WriteBytes(bw);
            }
        }

    }

}
