// This file was automatically generated by Beschi v0.2.0
// <https://github.com/sjml/beschi>
// Do not edit directly.


const _textDec = new TextDecoder('utf-8');
const _textEnc = new TextEncoder();

export class DataAccess {
    buffer: DataView;
    currentOffset: number;

    constructor(buffer: ArrayBuffer|DataView) {
        this.currentOffset = 0;
        if (buffer instanceof ArrayBuffer) {
            this.buffer = new DataView(buffer);
        }
        else {
            this.buffer = buffer;
        }
    }

    isFinished(): boolean {
        return this.currentOffset >= this.buffer.byteLength;
    }

    getByte(): number {
        const ret = this.buffer.getUint8(this.currentOffset);
        this.currentOffset += 1;
        return ret;
    }

    getBool(): boolean {
        return this.getByte() > 0;
    }

    getInt16(): number {
        const ret = this.buffer.getInt16(this.currentOffset, true);
        this.currentOffset += 2;
        return ret;
    }

    getUint16(): number {
        const ret = this.buffer.getUint16(this.currentOffset, true);
        this.currentOffset += 2;
        return ret;
    }

    getInt32(): number {
        const ret = this.buffer.getInt32(this.currentOffset, true);
        this.currentOffset += 4;
        return ret;
    }

    getUint32(): number {
        const ret = this.buffer.getUint32(this.currentOffset, true);
        this.currentOffset += 4;
        return ret;
    }

    getInt64(): bigint {
        const ret = this.buffer.getBigInt64(this.currentOffset, true);
        this.currentOffset += 8;
        return ret;
    }

    getUint64(): bigint {
        const ret = this.buffer.getBigUint64(this.currentOffset, true);
        this.currentOffset += 8;
        return ret;
    }

    getFloat32(): number {
        const ret = this.buffer.getFloat32(this.currentOffset, true);
        this.currentOffset += 4;
        return Math.fround(ret);
    }

    getFloat64(): number {
        const ret = this.buffer.getFloat64(this.currentOffset, true);
        this.currentOffset += 8;
        return ret;
    }

    getString(): string {
        const len = this.getByte();
        const strBuffer = new Uint8Array(this.buffer.buffer, this.currentOffset, len);
        this.currentOffset += len;
        return _textDec.decode(strBuffer);
    }


    setByte(val: number) {
        this.buffer.setUint8(this.currentOffset, val);
        this.currentOffset += 1;
    }

    setBool(val: boolean) {
        this.setByte(val ? 1 : 0);
    }

    setInt16(val: number) {
        this.buffer.setInt16(this.currentOffset, val, true);
        this.currentOffset += 2;
    }

    setUint16(val: number) {
        this.buffer.setUint16(this.currentOffset, val, true);
        this.currentOffset += 2;
    }

    setInt32(val: number) {
        this.buffer.setInt32(this.currentOffset, val, true);
        this.currentOffset += 4;
    }

    setUint32(val: number) {
        this.buffer.setUint32(this.currentOffset, val, true);
        this.currentOffset += 4;
    }

    setInt64(val: bigint) {
        this.buffer.setBigInt64(this.currentOffset, val, true);
        this.currentOffset += 8;
    }

    setUint64(val: bigint) {
        this.buffer.setBigUint64(this.currentOffset, val, true);
        this.currentOffset += 8;
    }

    setFloat32(val: number) {
        this.buffer.setFloat32(this.currentOffset, val, true);
        this.currentOffset += 4;
    }

    setFloat64(val: number) {
        this.buffer.setFloat64(this.currentOffset, val, true);
        this.currentOffset += 8;
    }

    setString(val: string) {
        const strBuffer = _textEnc.encode(val);
        this.setByte(strBuffer.byteLength);
        const arr = new Uint8Array(this.buffer.buffer);
        arr.set(strBuffer, this.currentOffset);
        this.currentOffset += strBuffer.byteLength;
    }
}

export enum MessageType {
  Vector3MessageType = 1,
  NewCharacterMessageType = 2,
  CharacterJoinedTeamType = 3,
}

export interface Message {
  getMessageType(): MessageType;
  writeBytes(dv: DataView, tag: boolean): void;
  getSizeInBytes(): number;
}
export interface MessageStatic {
  new(): Message;
  fromBytes(dv: DataView): Message | null;
}
function staticImplements<T>() {
  return (constructor: T) => {}
}

export function ProcessRawBytes(dv: DataView): Message[] {
  const da = new DataAccess(dv);
  const msgList: Message[] = [];
  while (!da.isFinished()) {
    const msgType: number = da.getByte();
    switch (msgType) {
      case 0:
        return msgList;
      case MessageType.Vector3MessageType:
        msgList.push(Vector3Message.fromBytes(da));
        break;
      case MessageType.NewCharacterMessageType:
        msgList.push(NewCharacterMessage.fromBytes(da));
        break;
      case MessageType.CharacterJoinedTeamType:
        msgList.push(CharacterJoinedTeam.fromBytes(da));
        break;
      default:
        throw new Error(`Unknown message type: ${msgType}`);
    }
  }
  return msgList;
}

export class Color {
  red: number = 0;
  green: number = 0;
  blue: number = 0;
  alpha: number = 0;

  static fromBytes(da: DataAccess): Color {
    const nColor = new Color();
    nColor.red = da.getFloat32();
    nColor.green = da.getFloat32();
    nColor.blue = da.getFloat32();
    nColor.alpha = da.getFloat32();
    return nColor;
  }

  writeBytes(da: DataAccess) {
    da.setFloat32(this.red);
    da.setFloat32(this.green);
    da.setFloat32(this.blue);
    da.setFloat32(this.alpha);
  }

}

export class Spectrum {
  defaultColor: Color = new Color();
  colors: Color[] = [];

  static fromBytes(da: DataAccess): Spectrum {
    const nSpectrum = new Spectrum();
    nSpectrum.defaultColor = Color.fromBytes(da);
    const colors_Length = da.getUint16();
    nSpectrum.colors = Array<Color>(colors_Length);
    for (let i2 = 0; i2 < colors_Length; i2++) {
      nSpectrum.colors[i2] = Color.fromBytes(da);
    }
    return nSpectrum;
  }

  writeBytes(da: DataAccess) {
    this.defaultColor.writeBytes(da);
    da.setUint16(this.colors.length);
    for (let i = 0; i < this.colors.length; i++) {
      let el = this.colors[i];
      el.writeBytes(da);
    }
  }

}

@staticImplements<MessageStatic>()
export class Vector3Message implements Message {
  x: number = 0;
  y: number = 0;
  z: number = 0;

  getMessageType() : MessageType { return MessageType.Vector3MessageType; }

  getSizeInBytes(): number {
    return 12;
  }

  static fromBytes(data: DataView|DataAccess): Vector3Message {
    let da: DataAccess;
    if (data instanceof DataView) {
      da = new DataAccess(data);
    }
    else {
      da = data;
    }
    try {
      const nVector3Message = new Vector3Message();
      nVector3Message.x = da.getFloat32();
      nVector3Message.y = da.getFloat32();
      nVector3Message.z = da.getFloat32();
      return nVector3Message;
    }
    catch (err) {
      throw new Error(`Could not read Vector3Message from offset ${da.currentOffset} (${err.name})`);
    }
  }

  writeBytes(data: DataView|DataAccess, tag: boolean): void {
    let da: DataAccess;
    if (data instanceof DataView) {
      da = new DataAccess(data);
    }
    else {
      da = data;
    }
    if (tag) {
      da.setByte(MessageType.Vector3MessageType);
    }
    da.setFloat32(this.x);
    da.setFloat32(this.y);
    da.setFloat32(this.z);
  }

}

@staticImplements<MessageStatic>()
export class NewCharacterMessage implements Message {
  id: bigint = 0n;
  characterName: string = "";
  strength: number = 0;
  intelligence: number = 0;
  dexterity: number = 0;
  goldInWallet: number = 0;
  nicknames: string[] = [];

  getMessageType() : MessageType { return MessageType.NewCharacterMessageType; }

  getSizeInBytes(): number {
    let size: number = 0;
    size += _textEnc.encode(this.characterName).byteLength;
    for (let nicknames_i=0; nicknames_i < this.nicknames.length; nicknames_i++) {
      size += 1 + _textEnc.encode(this.nicknames[nicknames_i]).byteLength;
    }
    size += 21;
    return size;
  }

  static fromBytes(data: DataView|DataAccess): NewCharacterMessage {
    let da: DataAccess;
    if (data instanceof DataView) {
      da = new DataAccess(data);
    }
    else {
      da = data;
    }
    try {
      const nNewCharacterMessage = new NewCharacterMessage();
      nNewCharacterMessage.id = da.getUint64();
      nNewCharacterMessage.characterName = da.getString();
      nNewCharacterMessage.strength = da.getUint16();
      nNewCharacterMessage.intelligence = da.getUint16();
      nNewCharacterMessage.dexterity = da.getUint16();
      nNewCharacterMessage.goldInWallet = da.getUint32();
      const nicknames_Length = da.getUint16();
      nNewCharacterMessage.nicknames = Array<string>(nicknames_Length);
      for (let i3 = 0; i3 < nicknames_Length; i3++) {
        nNewCharacterMessage.nicknames[i3] = da.getString();
      }
      return nNewCharacterMessage;
    }
    catch (err) {
      throw new Error(`Could not read NewCharacterMessage from offset ${da.currentOffset} (${err.name})`);
    }
  }

  writeBytes(data: DataView|DataAccess, tag: boolean): void {
    let da: DataAccess;
    if (data instanceof DataView) {
      da = new DataAccess(data);
    }
    else {
      da = data;
    }
    if (tag) {
      da.setByte(MessageType.NewCharacterMessageType);
    }
    da.setUint64(this.id);
    da.setString(this.characterName);
    da.setUint16(this.strength);
    da.setUint16(this.intelligence);
    da.setUint16(this.dexterity);
    da.setUint32(this.goldInWallet);
    da.setUint16(this.nicknames.length);
    for (let i = 0; i < this.nicknames.length; i++) {
      let el = this.nicknames[i];
      da.setString(el);
    }
  }

}

@staticImplements<MessageStatic>()
export class CharacterJoinedTeam implements Message {
  characterID: bigint = 0n;
  teamName: string = "";
  teamColors: Color[] = [];

  getMessageType() : MessageType { return MessageType.CharacterJoinedTeamType; }

  getSizeInBytes(): number {
    let size: number = 0;
    size += _textEnc.encode(this.teamName).byteLength;
    size += this.teamColors.length * 16;
    size += 11;
    return size;
  }

  static fromBytes(data: DataView|DataAccess): CharacterJoinedTeam {
    let da: DataAccess;
    if (data instanceof DataView) {
      da = new DataAccess(data);
    }
    else {
      da = data;
    }
    try {
      const nCharacterJoinedTeam = new CharacterJoinedTeam();
      nCharacterJoinedTeam.characterID = da.getUint64();
      nCharacterJoinedTeam.teamName = da.getString();
      const teamColors_Length = da.getUint16();
      nCharacterJoinedTeam.teamColors = Array<Color>(teamColors_Length);
      for (let i3 = 0; i3 < teamColors_Length; i3++) {
        nCharacterJoinedTeam.teamColors[i3] = Color.fromBytes(da);
      }
      return nCharacterJoinedTeam;
    }
    catch (err) {
      throw new Error(`Could not read CharacterJoinedTeam from offset ${da.currentOffset} (${err.name})`);
    }
  }

  writeBytes(data: DataView|DataAccess, tag: boolean): void {
    let da: DataAccess;
    if (data instanceof DataView) {
      da = new DataAccess(data);
    }
    else {
      da = data;
    }
    if (tag) {
      da.setByte(MessageType.CharacterJoinedTeamType);
    }
    da.setUint64(this.characterID);
    da.setString(this.teamName);
    da.setUint16(this.teamColors.length);
    for (let i = 0; i < this.teamColors.length; i++) {
      let el = this.teamColors[i];
      el.writeBytes(da);
    }
  }

}

export const MessageTypeMap = new Map<MessageType, { new(): Message }>([
  [MessageType.Vector3MessageType, Vector3Message],
  [MessageType.NewCharacterMessageType, NewCharacterMessage],
  [MessageType.CharacterJoinedTeamType, CharacterJoinedTeam],
]);

